# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

#box settings
  config.vm.box = "ubuntu/bionic64"

 config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
     # Customize the amount of memory on the VM:
     vb.memory = "1024"
     vb.name = "vm_for_pr_b6"
     #set video memory size
     vb.customize ["modifyvm", :id, "--vram", "32"]
  end

#if you need the source box update
  config.vm.box_check_update = false

#network settins
  #config.vm.network "forwarded_port", guest: 80, host: 8080
  #config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  #config.vm.network "private_network", ip: "192.168.33.10"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

    
  #Provision settings
  config.vm.provision "shell", inline: <<-SHELL
	export DEBIAN_FRONTEND=noninteractive
	export LANGUAGE=en_US.UTF-8
	export LANG=en_US.UTF-8
	export LC_ALL=en_US.UTF-8
	locale-gen en_US.UTF-8
#	sudo dpkg-reconfigure locales
	sudo ex +"%s@DPkg@//DPkg" -cwq /etc/apt/apt.conf.d/70debconf
	sudo dpkg-reconfigure debconf -f noninteractive -p critical
	sudo apt-get update
	sudo apt-get install -y python3 python3-pip python-psycopg2 python3-django
  SHELL
	config.vm.provision "file", source: "emptyfile", destination: "emptyfile"
end
